[package]

name = "pushfour-rust"
version = "0.0.1"
authors = [ "Andrew Matteson <amatteson3@gmail.com>" ]

[dependencies]
time = "0.1"

[dependencies.minimax]
git = "http://github.com/aromatt/rust-minimax"
version = "0.4.0"

