[package]

name = "pushfour-rust"
version = "0.0.1"
authors = [ "Andrew Matteson <amatteson3@gmail.com>" ]

[lib]
name = "pushfour"

[dependencies]
regex = "0.1"
lazy_static = "0.1.*"
rand = "0.3"

[dependencies.minimax]
git = "http://github.com/aromatt/rust-minimax"
version = "0.6.0"
